### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bootstraponline**
I think this tip should be documented somewhere so people know it's easy to modify the code even though a transpiler is in use.

### CODE REVIEW

**Comment by Jonahss** [comment]
I actually suggest cloning the repo, then using `npm link` in that directory. Then cd to appium and run `npm link appium-xcode`. It symlinks node_modules/appium-xcode to whatever directory you cloned and ran `npm-link` from.

That's great, until your clone gets behind master and you don't unlink it (you can always just blow away node_modules and reinstall)

**Comment by bootstraponline** [comment]
Ok, even better. I will update this PR.

**Comment by bootstraponline** [comment]
Updated. I left in the tip about just cding into the module since for small throwaway edits (such as adding one time use logging statements) the linking process is a pain.

**Comment by Jonahss** [comment]
cool :D

**Comment by jlipps** [comment]
:+1:

**Pull request merged**
