### PR TITLE
use lodash memoize, instead of implementing a cache

### PR DESCRIPTION
**Pull request by Jonahss**
Here we're using lodash's memoize instead of the cache I implemented manually.

Does the way I used the `_.memoize` function in the function declaration ok with everybody? @sebv 

I'll have to merge this with #3 but just checking if the way I did it is ok.

### CODE REVIEW

**Comment by jlipps** [comment]
:+1:

**Comment by Jonahss** [comment]
@sebv I merged this to unblock myself, but if you think there's a better way to handle the syntax or a better module to use, I'll redo it :)

**Comment by sebv** [comment]
Yeah the syntax looks good. This issue you may have is that `retry` should have similar syntax as memoize (ie directly acting on the function). You may want to add a method to asyncbox to do that.

I am not sure about making all the functions `const`, can you still mock them?

**Comment by Jonahss** [comment]
Good question. Hm.

**Pull request merged**
