### PR TITLE
feat: ship type declarations

### PR DESCRIPTION
**Pull request by boneskull**
This PR adds type declaration generation. It does not compile via `tsc` (that can be done later).

Also needed to fix some docstrings, so I did that.

### CODE REVIEW

**Comment by boneskull** [comment]
Note that I replaced usages of `log.errorAndThrow` since that method is essentially incompatible with TypeScript (because it's not obvious to the compiler that execution no longer continues once the method is called).  We should probably deprecate that method.

**Review by mykola-mokhnach — APPROVED** [review]

**Review by KazuCocoa — APPROVED** [review]

**Comment by jlipps** [comment]
maybe we could replace it with a function like `log.makeError('foo')` so that we could at least do this:

```js
throw log.makeError('foo');
```

instead of what would normally be 3 lines:

```js
const msg = 'foo';
log.error(msg);
throw new Error(msg);
```

**Comment by boneskull** [comment]
@jlipps Yeah.  See appium/appium#18414

**Comment by boneskull** [comment]
Current dependencies on/for this PR:
* master
  * **PR #81** <a href="https://app.graphite.dev/github/pr/appium/appium-xcode/81" target="_blank">Graphite</a>  👈
    * **PR #83** <a href="https://app.graphite.dev/github/pr/appium/appium-xcode/83" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/appium/appium-xcode/81?utm_source=stack-comment).

**Pull request merged**
